version = 1

test_patterns = ["src/tests/**"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "prettier"
enabled = true