openapi: 3.0.0
info:
  title: 1. Version 1
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
tags:
  - name: Import product
  - name: Price Quotation
  - name: Supplier
  - name: 'Replicate: Flow nhập hàng'
    description: |-
      # Note

      - Đây là quy trình tạm thời để nhập hàng
      - \*Supplier\* mới có thể tạo supplier trước bước 3 của quy trình
  - name: 'Replicate: Provide API'
    description: |-
      ## Danh sách Api cung cấp cho nhóm khác

      | API name | Group |
      | --- | --- |
      | Lấy giá nhập hàng | SP_06:Product |
      | Lấy danh sách nhà cung cấp | SP_06:Product |
paths:
  /import:
    get:
      tags:
        - Import product
      summary: get all Import request join
      parameters:
        - name: status
          in: query
          schema:
            type: string
          example: COMPLETED
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - 'Replicate: Flow nhập hàng'
      summary: '1. ImpP:Create: Tạo yêu cầu nhập hàng'
      description: |-
        ``` json
        {
            // Định danh sản phẩm
            "product_id": 2,
            "subproduct_id": 4,
            // cập nhật lại ở step 3
            "supplier_id": null,
            "price_quotation_id": null,
            "total_cost": 0,
            // cố định
            "status": "REQUEST",
            //
            "quantity": 1000,
            "note": "abc",
            "created_by": "",
            "updated_by": ""
        }

        ```
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                product_id: 2
                subproduct_id: 4
                supplier_id: null
                price_quotation_id: null
                total_cost: 0
                status: REQUEST
                quantity: 1000
                note: abc
                created_by: ''
                updated_by: ''
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /import/history:
    get:
      tags:
        - Import product
      summary: get all Import request join Copy
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /import/{id}:
    get:
      tags:
        - Import product
      summary: Find by id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - 'Replicate: Flow nhập hàng'
      summary: '6. ImpP:Upd: Xác nhận nhập hàng thành công'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: COMPLETED
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /import/2:
    delete:
      tags:
        - Import product
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /getHistory/statistical:
    get:
      tags:
        - Import product
      summary: Get History Statistical
      parameters:
        - name: year
          in: query
          schema:
            type: integer
          example: '2022'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /import/count-per-month/:
    get:
      tags:
        - Import product
      summary: Get History Statistical Copy
      parameters:
        - name: year
          in: query
          schema:
            type: integer
          example: '2023'
        - name: quarter
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /price-quotation/:
    get:
      tags:
        - 'Replicate: Flow nhập hàng'
      summary: '4. PQ:GetAll: Danh sách ycnh với import_id'
      parameters:
        - name: import_id
          in: query
          schema:
            type: integer
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - 'Replicate: Flow nhập hàng'
      summary: '3. PQ:Create: Tạo báo giá cho ycnh đã ACCEPT'
      description: |-
        ``` json
        ```json
        {
            "import_id": 12,     // id từ step 1
            "supplier_id": 1,    // id ncc đã tạo từ trước

            "product_id": 4,    // định danh sản phẩm
            "subproduct_id": 1,    // lấy từ step 1

            "unit_price": 150,
            "note": "",

            "created_by": null,
            "updated_by": null
        }
        ```

        ```
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                import_id: 2
                supplier_id: 1
                product_id: 4
                subproduct_id: 1
                unit_price: 250
                note: ''
                created_by: null
                updated_by: null
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /price-quotation/1:
    get:
      tags:
        - Price Quotation
      summary: get by id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Price Quotation
      summary: update by id
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '""'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Price Quotation
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /supplier/:
    get:
      tags:
        - 'Replicate: Provide API'
      summary: Danh sách nhà cung cấp
      parameters:
        - name: startAt
          in: query
          schema:
            type: string
          example: '2022-01-09T17:22:02.643Z'
        - name: endAt
          in: query
          schema:
            type: string
          example: '2023-12-17'
        - name: name
          in: query
          schema:
            type: string
          example: a
        - name: phone
          in: query
          schema:
            type: integer
          example: '8'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Supplier
      summary: create supplier
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Bách Khoa 7
                phone: '1234567890'
                email: harvardDaiCoViet@hust.vn
                address: So 1 Viet Nam
                created_by: a
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /supplier/5:
    get:
      tags:
        - Supplier
      summary: find by id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /supplier/2:
    put:
      tags:
        - Supplier
      summary: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Bách Khoa
                phone: '09999999999'
                email: harvardDaiCoViet@hust.vn
                address: So 1 Viet Nam
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Supplier
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /supplier/count-per-month:
    get:
      tags:
        - Supplier
      summary: Get Statistical
      parameters:
        - name: year
          in: query
          schema:
            type: integer
          example: '2023'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /import/get-price:
    get:
      tags:
        - 'Replicate: Provide API'
      summary: Lấy giá nhập hàng
      parameters:
        - name: groupBy
          in: query
          schema:
            type: string
          example: product_id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
